version: '3.9'

services:
  app:
    build: .
    container_name: sync-service-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16-alpine
    container_name: sync-service-postgres
    environment:
      POSTGRES_DB: sync_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: sync-service-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
