version: '3.9'
services:
  app:
    build: .
    container_name: fedportal1-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    container_name: fedportal1-postgres
    security_opt:
      - no-new-privileges:false
    environment:
      POSTGRES_DB: sync_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sync_db"]
      interval: 5s
      timeout: 5s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: fedportal1-rabbitmq
    security_opt:
      - no-new-privileges:false
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  postgres_data:
    name: fedportal1_postgres_data
  rabbitmq_data:
    name: fedportal1_rabbitmq_data