"""initial

Revision ID: 001
Revises:
Create Date: 2025-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Значения в нижнем регистре — в точности как EntityType.value
ENTITY_TYPE_VALUES = [
    'organization',
    'department',
    'order',
    'event',
    'activity',
    'program-group',
    'certificate',
    'program-group-financing-source',
    'parents',
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    entity_type_enum = sa.Enum(*ENTITY_TYPE_VALUES, name='entity_type', create_type=True)
    entity_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'sync_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('request_data', sa.JSON(), nullable=False),
        sa.Column('response_data', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_logs'))
    )
    op.create_table(
        'synced_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('object_id', sa.Integer(), nullable=False),
        sa.Column('entity_type', entity_type_enum, nullable=False),
        sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_synced_records')),
        sa.UniqueConstraint('entity_type', 'object_id', name='uq_synced_records_entity_type_object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synced_records')
    op.drop_table('sync_logs')
    sa.Enum(name='entity_type').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
